"""empty message

Revision ID: babe191cc083
Revises: 26cad099ac69
Create Date: 2025-10-16 15:06:08.894430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'babe191cc083'
down_revision = '26cad099ac69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocabulary_word', schema=None) as batch_op:
        batch_op.create_unique_constraint('vocabulary_unique', ['uid', 'word'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocabulary_word', schema=None) as batch_op:
        batch_op.drop_constraint('vocabulary_unique', type_='unique')

    # ### end Alembic commands ###
