"""add user table

Revision ID: de79dc5ccad7
Revises: babe191cc083
Create Date: 2025-11-05 14:48:03.727928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de79dc5ccad7'
down_revision = 'babe191cc083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('wechat_openid', sa.String(length=128), nullable=True),
    sa.Column('wechat_unionid', sa.String(length=128), nullable=True),
    sa.Column('nickname', sa.String(length=128), nullable=True),
    sa.Column('avatar', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('gmt_create', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('gmt_update', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkid'),
    sa.UniqueConstraint('phone', name='user_phone_unique'),
    sa.UniqueConstraint('wechat_openid', name='user_wechat_openid_unique')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
